version: '3'
services:
  jupyterlab:
    container_name: deepchem 
    #image: deepchemio/deepchem:2.3.0
    build: .
    volumes:
      - "./:/work"
    ports:
      - "8888:8888"
    command:
       bash -c "source activate deepchem &&
       jupyter-lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"